name: Build Debian package
description: Build Debian package from source for selected target release
branding:
  color: red
  icon: package
inputs:
  source_directory:
    description: Directory where Debian sources are, relative to workspace
    required: false
    default: ./
  artifacts_directory:
    description: Directory where build artifacts will be placed, relative to workspace
    required: false
    default: ./
  additional_repositories:
    description: Additional APT repositories, one per line
    required: false
runs:
  using: node12
  main: main.js
